### ISSUE TITLE
Issues fail to sync (new or updates) on v1.2.1

### ISSUE THREAD

**Issue by jtracey93** [a11smiles/GitSync#11]
Action Example from ALZ-Bicep Repo

```
name: Sync Issues to Azure DevOps Work Items

on:
  issues:
    types: [opened, closed, deleted, reopened, edited, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    if: github.repository == 'Azure/ALZ-Bicep'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GitHub/ADO Sync
        uses: a11smiles/GitSync@v1.2.1
        env:
          ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
          config_file: './.github/actions-config/gh-ado-sync-config.json'
        with:
          ado: ${{ secrets.ADO_MAPPINGS_HANDLES }}

```

Issue 

![image](https://user-images.githubusercontent.com/41163455/199456176-a8f5e7ea-2129-4e7a-a161-ab66d83529e4.png)

Link to workflow run https://github.com/Azure/ALZ-Bicep/actions/runs/3376390222/jobs/5604055209
